Fix NoSuchMethodError when upading albums. Fixes #2.
This error was caused by adding null to the displayed list of albums.
(If no shared albums exist for the user, the call returns null).

This adds a null check when adding albums.

Change-Id: I3450e0ed066bcf388948dbc31d9745f565f29c55